export const environment = {
  production: false,
  apiKey: 'fdca3397',
  apiUrl: 'https://www.omdbapi.com/',
  movie: [
    'Inception',
    'The Matrix',
    'Interstellar',
    'Gladiator',
    'The Dark Knight',
    'Pulp Fiction',
    'Fight Club',
    'Forrest Gump',
    'The Shawshank Redemption',
    'The Godfather',
    'Spirited Away',
    'Parasite',
    'The Lion King',
    'Back to the Future',
    'Alien',
    'The Shining',
    'Blade Runner 2049',
    'Avengers: Endgame',
    'Joker',
    'Coco',
    'Whiplash',
    'The Prestige',
    'Memento',
    'The Departed',
    'The Green Mile',
    'Leon',
    'Seven',
    'The Pianist',
    'American History X',
    'Terminator 2',
  ],
  series: [
    'Breaking Bad',
    'Game of Thrones',
    'Stranger Things',
    'Chernobyl',
    'Sherlock',
    'The Crown',
    'The Wire',
    'Black Mirror',
    'Dark',
    'The Office',
    'Friends',
    'The Mandalorian',
    'Better Call Saul',
    'Succession',
    'The Bear',
    'Fargo',
    'True Detective',
    'Mindhunter',
    'Narcos',
    'Peaky Blinders',
    'The Boys',
    'The Witcher',
    'The Last of Us',
    'House of the Dragon',
    'Ted Lasso',
    'The White Lotus',
    'Severance',
    'Beef',
    'Mr. Robot',
    'Westworld',
  ],
  episode: [
    'Ozymandias',
    'Battle of the Bastards',
    'The Rains of Castamere',
    'Hardhome',
    'San Junipero',
    'White Christmas',
    'Blink',
    'The Reichenbach Fall',
    'The Constant',
    'Pine Barrens',
    'Face Off',
    "Connor's Wedding",
    'Long, Long Time',
    'Dear Billy',
    'The Suitcase',
    'Mizumono',
    "Everyone's Waiting",
    'Abyssinia, Henry',
    'Through the Looking Glass',
    'The Inner Light',
    'All Good Things...',
    'Saul Gone',
    'Chicanery',
    'The Winds of Winter',
    'The Mountain and the Viper',
    'Point and Shoot',
    '407 Proxy Authentication Required',
    'Hero',
    'Middle Ground',
    'College',
  ],
};
